version: '3.3'
services:
    terminal:
        volumes:
          - ./data:/home/kasm-user/.local/share/Anki2
        ports:
            - '6901:6901'
        environment:
            - VNC_PW=password
        image: 'kasmweb/terminal:1.12.0-anki2'
